[env]
TERM = "xterm-256color"

[window]
#padding.x = 10
#padding.y = 10

#decorations = "Buttonless"

[font]
normal.family = "MesloLGS Nerd Font Mono"
#size = 9.0

[general]
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[selection]
save_to_clipboard = true
