[env]
TERM = "xterm-256color"

[window]
#padding.x = 10
#padding.y = 10

#decorations = "Buttonless"

[font]
#normal.family = "MesloLGS Nerd Font Mono"
#size = 9.0

[general]
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[selection]
save_to_clipboard = true
