#
# bash improvements
#
set -o vi

#
# local path
#
export PATH="${PATH}:$HOME/bin/misc"

# depot tools
# export PATH=~/bin/depot_tools:"$PATH"

#
# Git
#
source /usr/share/bash-completion/completions/git
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
export PS1="\[\033[00m\]\u@\h\[\033[01;33m\] \w \[\033[31m\]\$(parse_git_branch)\[\033[00m\]$\[\033[00m\] "

#PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\u@\h:\w\$ "
#export PS1

#
# Android
#
# Android adb auto-completion
if [ -e ~/src/android/android-completion/android ] ; then
    source ~/src/android/android-completion/android
fi
#export NDK_ROOT=~/androiddev/android-ndk-r13
#export NDK_TOOLCHAIN_VERSION=4.9
#export NDK_TOOLCHAIN_VERSION=clang
export ANDROID_HOME=~/Library/Android/sdk
export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/20.1.5948944
export ANDROID_NDK=$ANDROID_HOME/ndk-bundle

export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/build-tools/28.0.3
export PATH=$PATH:$ANDROID_NDK_HOME

#
# Cocos2d-x
#
export COCOS_CONSOLE_ROOT="/mnt/sources/progs/cocos2d-x/tools/cocos2d-console/bin"
export PATH=$COCOS_CONSOLE_ROOT:$PATH
export COCOS_X_ROOT="/mnt/sources/progs"
export PATH=$COCOS_X_ROOT:$PATH
export COCOS_TEMPLATES_ROOT="/mnt/sources/progs/cocos2d-x/templates"
export PATH=$COCOS_TEMPLATES_ROOT:$PATH
export ANDROID_SDK_ROOT=$ANDROID_HOME
export NDK_ROOT=$ANDROID_NDK_HOME


#
# Qt 6
#
export PATH=~/Qt/6.2.2/gcc_64/bin:~/Qt/Tools/QtCreator/bin:$PATH


#
# VICE, contiki, cc65
#
#export PATH=$PATH:~/Applications/VICE/tools
export CC65_HOME=~/src/c64/cc65
export CONTIKI=~/src/c64/contiki
export C1541=/usr/local/bin/c1541
export AC=~/tmp
export DIR2ATR=~/tmp


#
# nvim, not vi as default editor
#
export EDITOR=nvim
export VISUAL=$EDITOR

#ESP32
#export PATH=$PATH:$HOME/esp/xtensa-esp32-elf/bin
export IDF_PATH=$HOME/esp/esp-idf
export ESPPORT=/dev/ttyUSB0
export ESPBAUD=115200
export MONITORBAUD=115200


#platformio
#export PATH=$PATH:~/.platformio/penv/bin

#C64 misc tools
export PATH=$PATH:$HOME/progs/c64-misc/tools

#Atari ST / Amiga tools
export VBCC=$HOME/bin/vbcc
export PATH=$PATH:$HOME/bin/vbcc/bin
export NDK=$VBCC/targets/m68k-amigaos/ndk
export NDK_INC=$NDK/Include/include_h
export NDK_LIB=$NDK/Include/linker_libs

#Go
export GOPATH=~/go
export PATH=$PATH:~/go/bin
export GOBIN=~/go/bin

#Rust
export PATH=$PATH:~/.cargo/bin/

# Oracle Java
#export PATH=/usr/lib/jvm/jdk-13.0.1/bin/:$PATH

# CircuitPython & others
export PATH=~/bin/gcc-arm-none-eabi-10.3-2021.10/bin/:$PATH

# PICO SDK
export PICO_SDK_PATH=~/src/rpi/pico-sdk/

# VBCC / VASM / VLINK
export VBCC=~/bin/vbcc
export PATH=$PATH:$VBCC

# Powerline
powerline-daemon -q
export POWERLINE_BASH_CONTINUATION=1
export POWERLINE_BASH_SELECT=1
source /usr/share/powerline/bindings/bash/powerline.sh

# Flutter
export PATH=$PATH:~/bin/flutter/bin

# Zephyr
export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
export ZEPHYR_SDK_INSTALL_DIR=/home/riq/bin/zephyr-sdk-0.13.2

# ModusToolbox
export CY_TOOLS_PATHS=~/bin/ModusToolbox/tools_3.0
